name: Create Release and Package TARs

on:
  push:
    tags:
      - 'v*'
      - 'test-v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create client.tar.gz
        run: tar -czvf client.tar.gz ./client

      - name: Create server.tar.gz
        run: tar -czvf server.tar.gz ./server

      - name: Create details.json
        run: |
          echo '{
            "version": "${{ github.ref_name }}",
            "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/client.tar.gz",
            "transfer_params": {
              "method": "wifi_ap",
              "ssid": "PicoUpdateAP",
              "password": "un_password_seguro"
            }
          }' > details.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ startsWith(github.ref, 'refs/tags/test-v') }}
          files: |
            client.tar.gz
            server.tar.gz
            details.json
